name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Heroku
      uses: actions/heroku@1.0.0
    - name: npm install, test, build, and push to heroku
      run: |
          npm ci
          npm test --if-present
          npm run build --if-present
          heroku login
          git push heroku master
      env:
        CI: true
